import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
const roboto = Roboto_Mono({
  weight: "400",
  subsets: ["latin"],
});
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="no-scrollbar">
      <body className={`flex justify-center ${roboto.className}`}>
        {children}
      </body>
    </html>
  );
}
